steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/good-food-454413/api-service-repository/api-service:$SHORT_SHA',
        '.',
      ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/good-food-454413/api-service-repository/api-service:$SHORT_SHA',
      ]

  # Deploy to Cloud Run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     [
  #       'run',
  #       'deploy',
  #       'edt',
  #       '--image=europe-west1-docker.pkg.dev/good-food-454413/api-service-repository/api-service:$SHORT_SHA',
  #       '--region',
  #       'europe-west1',
  #       '--platform',
  #       'managed',
  #     ]

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'container',
        'clusters',
        'get-credentials',
        'good-food-cluster',
        '--zone',
        'europe-west1-b',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/api-service',
        'api-service=europe-west1-docker.pkg.dev/good-food-454413/api-service-repository/api-service:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'restart', 'deployment/api-service']
